name: Deploy Website to S3

on:
  push:
    branches:
      - main  # This should be your repo's branch that triggers the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # This uses the stable version v2 of the checkout action

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master  # This uses the 'master' branch of the action repo
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: '' # Leave this blank to sync the entire repository
